---
- name: Enable the zfs repo
  yum_repository:
    name: ZFS
    description: ZFS YUM repo
    baseurl: http://download.zfsonlinux.org/epel/7.4/$basearch/
    gpgcheck: false
    gpgkey: http://pgp.mit.edu/pks/lookup?search=0xF14AB620&op=index&fingerprint=on

- name: Install ZFS packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - kernel-devel
    - zfs

- name: Enable ZFS kernel modules
  modprobe:
    name: zfs
    state: present

- name: Enable ZFS at bootup
  copy:
    content: "zfs"
    dest: /etc/modules-load.d/zfs.conf
    owner: root
    group: root
    mode: 0644
