---
- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Add Site Config
  template:
    src: reverseproxy.conf.j2
    dest: "/etc/nginx/conf.d/{{ item.key }}.conf"
    owner: root
    group: root
  with_dict: "{{ nginx_revproxy_sites }}"
  notify:
    - restart nginx

- name: Open firewalld
  firewalld:
    service: "{{ item }}"
    immediate: true
    permanent: true
    state: enabled
  with_items:
    - http
    - https

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: true
