---
nginx_revproxy_sites:                                         # List of sites to reverse proxy
  example.com:                                                # Domain name
    domains:                                                  # List of server_name aliases
      - example.com
      - www.example.com
    upstreams:                                                # List of Upstreams
      - { backend_address: 192.168.0.100, backend_port: 80 }
    hsts_max_age: 63072000                                    # Set HSTS header with max-age defined
  test.com:                                                # Domain name
    domains:                                                  # List of server_name aliases
      - test.com
      - www.test.com
    upstreams:                                                # List of Upstreams
      - { backend_address: 192.168.0.200, backend_port: 80 }
    hsts_max_age: 63072000
