---
- name: Install IUS repo.
  yum:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: latest

- name: Import IUS GPG key
  rpm_key:
    key: http://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY
    state: present
