---
- name: Install all necessary packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - "@Development tools"
    - curl
    - git
    - httpry
    - devscripts
    - automake
    - libtool
    - autoconf
    - cdbs
    - debhelper
    - dh-autoreconf
    - dpkg-dev
    - gettext
    - fakeroot
    - pcre
    - pcre-devel
    - zlib
    - zlib-devel
    - readline
    - readline-devel
    - ncurses
    - ncurses-devel
    - openssl
    - openssl-devel
    - udns
    - udns-devel
    - libev
    - libev-devel
    - pkgconfig
    - gd
    - gd-devel
    - geoip
    - geoip-devel

- name: Disable IPv6 with sysctl
  sysctl:
    name: "{{ item }}"
    value: 1
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Create lancache group
  group:
    name: lancache

- name: Create lancache user
  user:
    name: lancache
    group: lancache

- name: Create all necessary directories
  file:
    path: "/srv/lancache/{{ item }}"
    state: directory
    mode: 0777
    owner: lancache
    group: lancache
  with_items:
    - logs/Errors
    - logs/Keys
    - logs/Access
    - data/apple
    - data/microsoft
    - data/installs
    - data/other
    - data/tmp
    - data/hirez
    - data/origin
    - data/riot
    - data/gog
    - data/sony
    - data/steam
    - data/wargaming
    - data/arenanetworks
    - data/uplay
    - data/glyph
    - data/zenimax
    - data/digitalextremes
    - data/pearlabyss

- name: Increase queue listen size permanently
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^net\.core\.somaxconn'
    line: "net.core.somaxconn={{ somaxconn }}"
  register: sys_somaxconn

- name: Increase queue listen size now
  command: sysctl -w net.core.somaxconn={{ somaxconn }}
  when: sys_somaxconn.changed

- name: Find max open files
  command: cat /proc/sys/fs/file-max
  register: file_max

- name: Increase max files in sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^fs\.file-max'
    line: "fs.file-max={{ file_max.stdout }}"
  register: sys_filemax

- name: Increase max files now
  command: sysctl -w fs.file-max={{ file_max.stdout }}
  when: sys_filemax.changed

- name: Set systemd default limit
  lineinfile:
    dest: "/etc/systemd/{{ item }}"
    regexp: '^#?DefaultLimitNOFILE'
    line: "DefaultLimitNOFILE=infinity"
  with_items:
    - user.conf
    - system.conf

- name: Increase security limits
  template:
    src: "lancache_limits.conf"
    dest: "/etc/security/limits.d/lancache_limits.conf"
    owner: root
    group: root
    mode: 0644
