---
- name: Create all necessary directories
  file:
    path: "/srv/lancache/{{ item }}"
    state: directory
    mode: 0777
    owner: lancache
    group: lancache
  with_items:
    - logs/Errors
    - logs/Keys
    - logs/Access
    - data/apple
    - data/microsoft
    - data/installs
    - data/other
    - data/tmp
    - data/hirez
    - data/origin
    - data/riot
    - data/gog
    - data/sony
    - data/steam
    - data/wargaming
    - data/arenanetworks
    - data/uplay
    - data/glyph
    - data/zenimax
    - data/digitalextremes
    - data/pearlabyss
    - data/blizzard
    - data/enmasse

- name: Create symlink for LANcache logs
  file:
    src: /srv/lancache/logs
    dest: /var/log/lancache
    state: link

- name: Clone git LANcache project
  git:
    repo: http://github.com/bntjah/lancache
    dest: "{{ base_folder }}"
    force: true

- name: Replace aliases by ip  
  replace:
    path: "{{ base_folder }}/hosts"
    regexp: "{{ item.search }}"
    replace: "{{ item.replace }}"
  loop:
    - { search: 'lc-hostname', replace: '{{ inventory_hostname }}' }
    - { search: 'lc-host-proxybind', replace: '{{ ip }}' }
    - { search: 'lc-host-arena', replace: '{{ ip_arena }}' }
    - { search: 'lc-host-apple', replace: '{{ ip_apple }}' }
    - { search: 'lc-host-blizzard', replace: '{{ ip_blizzard }}' }
    - { search: 'lc-host-hirez', replace: '{{ ip_hirez }}' }
    - { search: 'lc-host-glyph', replace: '{{ ip_glyph }}' }
    - { search: 'lc-host-gog', replace: '{{ ip_gog }}' }
    - { search: 'lc-host-microsoft', replace: '{{ ip_microsoft }}' }
    - { search: 'lc-host-origin', replace: '{{ ip_origin }}' }
    - { search: 'lc-host-riot', replace: '{{ ip_riot }}' }
    - { search: 'lc-host-steam', replace: '{{ ip_steam }}' }
    - { search: 'lc-host-sony', replace: '{{ ip_sony }}' }
    - { search: 'lc-host-enmasse', replace: '{{ ip_enmasse }}' }
    - { search: 'lc-host-uplay', replace: '{{ ip_uplay }}' }
    - { search: 'lc-host-wargaming', replace: '{{ ip_wargaming }}' }
    - { search: 'lc-host-zenimax', replace: '{{ ip_zenimax }}' }
    - { search: 'lc-host-digitalextremes', replace: '{{ ip_digitalextremes }}' }
    - { search: 'lc-host-pearlabyss', replace: '{{ ip_pearlabyss }}' }

- name: Copy hosts file to /etc/hosts
  copy:
    src: "{{ base_folder }}/hosts"
    dest: /etc/hosts
    remote_src: true
    owner: root
    group: root
    mode: 0644

- name: Copy LANcache configuration
  command: "cp -rf {{ base_folder }}/conf/lancache /etc/nginx/"

- name: Copy LANcache vhosts
  command: "cp -rf {{ base_folder }}/conf/vhosts-enabled/ /etc/nginx/conf.d/"

- name: Copy Nginx config file
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- debug:
    msg: "{{ ip }}"

- name: Replace variables in vhost files
  replace:
    path: "/etc/nginx/conf.d/lancache-{{ item }}.conf"
    regexp: lc-host-proxybind
    replace: "{{ ip }}"
  loop:
    - apple
    - arenanetworks
    - blizzard
    - digitalextremes
    - enmasse
    - glyph
    - gog
    - hirez
    - microsoft
    - origin
    - pearlabyss
    - riot
    - sony
    - steam
    - uplay
    - wargaming
    - zenimax

- name: Change ownership of directorties
  file:
    path: "{{ item }}"
    owner: lancache
    group: lancache
    recurse: true
  with_items:
    - /srv/
    - /etc/nginx/
  notify:
    - Restart nginx
