---
- name: Add all required ip's to the main interface
  nmcli:
    type: ethernet
    conn_name: "{{ interface }}"
    ip4: "{{ ip }}/16,{{ ip_steam }}/16,{{ ip_riot }}/16,{{ ip_blizzard }}/16,{{ ip_hirez }}/16,{{ ip_origin }}/16,{{ ip_sony }}/16,{{ ip_microsoft }}/16,{{ ip_enmasse }}/16,{{ ip_gog }}/16,{{ ip_arena }}/16,{{ ip_wargaming }}/16,{{ ip_uplay }}/16,{{ ip_apple }}/16,{{ ip_glyph }}/16,{{ ip_zenimax }}/16,{{ ip_digitalextremes }}/16,{{ ip_pearlabyss }}/16"
    gw4: "{{ gw }}"
    dns4: "8.8.8.8,8.8.4.4"
    dns4_search: "lan"
    state: present		

- name: Disable edit default
  command: "nmcli con mod {{ interface }} ipv4.never-default no"

- name: Restart the interface
  command: "nmcli con up {{ interface }}"
