---
- name: Add all required ip's to the main interface
  nmcli:
    type: ethernet
    conn_name: "{{ main_interface }}"
    ip4: "{{ lc_ip }},{{ lc_ip_steam }},{{ lc_ip_riot }},{{ lc_ip_blizzard }},{{ lc_ip_hirez }},{{ lc_ip_origin }},{{ lc_ip_sony }},{{ lc_ip_microsoft }},{{ lc_ip_enmasse }},{{ lc_ip_gog }},{{ lc_ip_arena }},{{ lc_ip_wargaming }},{{ lc_ip_uplay }},{{ lc_ip_apple }},{{ lc_ip_glyph }},{{ lc_ip_zenimax }},{{ lc_ip_digitalextremes }},{{ lc_ip_pearlabyss }}"
    gw4: "{{ ip_gw }}"
    dns4: "8.8.8.8,8.8.4.4"
    dns4_search: "lan"
    state: present		

- name: Disable edit default
  command: "nmcli con mod {{ main_interface }} ipv4.never-default no"

- name: Restart the interface
  command: "nmcli con up {{ main_interface }}"
