---
- name: Clone Sniproxy from GIT
  git:
    repo: https://github.com/dlundquist/sniproxy
    dest: /tmp/sniproxy/
    force: true

- name: Get config file for Sniproxy
  get_url:
    url: https://raw.githubusercontent.com/OpenSourceLAN/origin-docker/master/sniproxy/sniproxy.conf
    dest: /etc/sniproxy.conf
    owner: root
    group: root
    mode: 0644

- name: Run ./autogen.sh for Sniproxy
  shell: "./autogen.sh"
  args:
    chdir: "/tmp/sniproxy"

- name: Run ./configure for Sniproxy
  shell: "./configure  --sbindir=/usr/sbin"
  args:
    chdir: "/tmp/sniproxy"

- name: Run make for Sniproxy
  shell: "make"
  args:
    chdir: "/tmp/sniproxy"

- name: Run make install for Sniproxy
  shell: "make install"
  args:
    chdir: "/tmp/sniproxy"

- name: Copy the systemd service file
  copy:
    src: sniproxy.service
    dest: /etc/systemd/system/sniproxy.service
    owner: root
    group: root
    mode: 0664

- name: Enable sniproxy.service
  systemd:
    name: sniproxy
    enabled: true

- name: Open firewalld port
  firewalld:
    service: https
    permanent: true
    immediate: true
    state: enabled
