---
galera_mysql_master_node: db1

galera_cluster_bind_address: 0.0.0.0
galera_cluster_bind_interface: 'enp0s3'

galera_cluster_name: 'lancluster'

galera_cluster_nodes_group: db

galera_ist_recv_addr: '{{ galera_cluster_bind_address }}'
galera_ist_recv_addr_port: '{{ galera_wsrep_node_address_port|int + 1 }}'

galera_ist_recv_bind: '{{ galera_cluster_bind_address }}'

galera_wsrep_node_address: '{{ galera_cluster_bind_address }}:4567'

mariadb_redhat_repo: 'http://yum.mariadb.org/{{ mariadb_version }}/{{ ansible_distribution|lower }}{{ ansible_distribution_major_version|int }}-amd64'
mariadb_redhat_repo_key: 'https://yum.mariadb.org/RPM-GPG-KEY-MariaDB'
mariadb_version: '10.3'

mariadb_oom_score_adjust: 0

mariadb_mysql_port: 3306

mariadb_mysql_root_password: 'root'
