---
- name: Set timezone to Europe/Brussels
  timezone:
    name: Europe/Brussels

- name: Add EPEL repository
  yum_repository:
    name: EPEL
    description: EPEL repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest

- name: Install base packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - git
    - rsync
    - sudo
    - tcpdump
    - curl
    - wget
    - vim
    - ntp
    - lsof
    - info
    - logrotate
    - rsyslog
    - coreutils
    - findutils
    - gzip
    - hostname
    - iproute
    - sed
    - tar
    - bind-utils
    - chrony
    - htop
    - iotop
    - iftop
    - nload
    - net-tools
    - iperf
    - strace
    - tuned
    - firewalld
    - dbus
    - NetworkManager-glib

- name: Template /etc/chrony.conf
  template:
    src: etc/chrony.conf
    dest: /etc/chrony.conf
    owner: root
    mode: 0644
  notify:
    - Restart chronyd

- name: Add ntp to firewalld
  firewalld:
    service: ntp
    immediate: true
    permanent: true
    state: enabled

- name: Create the authorized_keys file
  template:
    src: root/ssh/authorized_keys
    dest: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- name: Edit soft limits
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '\*\s+soft\s+nofile'
    line: '* soft nofile 65536'

- name: Edit hard limits
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '\*\s+hard\s+nofile'
    line: '* hard nofile 65536'

- name: Increase queue listen size permanently
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^net\.core\.somaxconn'
    line: "net.core.somaxconn={{ system.somaxconn }}"
  register: sys_somaxconn

- name: Increase queue listen size now
  command: sysctl -w net.core.somaxconn={{ system.somaxconn }}
  when: sys_somaxconn.changed

- name: Find max open files
  command: cat /proc/sys/fs/file-max
  register: file_max

- name: Increase max files in sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: '^fs\.file-max'
    line: "fs.file-max={{ file_max.stdout }}"
  register: sys_filemax

- name: Increase max files now
  command: sysctl -w fs.file-max={{ file_max.stdout }}
  when: sys_filemax.changed

- name: Set systemd default limit
  lineinfile:
    dest: "/etc/systemd/{{ item }}"
    regexp: '^#?DefaultLimitNOFILE'
    line: "DefaultLimitNOFILE=infinity"
  with_items:
    - user.conf
    - system.conf

- name: Enable tuned throughput-performance profile
  shell: "tuned-adm profile throughput-performance"
